import type { Inspection, Rule } from './types';

export const MOCK_RULES: Rule[] = [
  {
    id: 'LM-R001',
    name: 'Mandatory Declarations — General',
    description: 'Every package shall bear the name and address of the manufacturer, packer or importer, the common or generic name of the commodity, the net quantity, month and year of manufacture or packing, retail sale price (MRP), and consumer care details.',
    category: 'Packaged Commodities',
    version: '2026.1',
    effectiveDate: '2026-01-01',
    source: 'Legal Metrology (Packaged Commodities) Rules',
    mandatory: true,
  },
  {
    id: 'LM-R002',
    name: 'Net Quantity Declaration',
    description: 'Net quantity shall be declared in standard units — weight (grams/kilograms), volume (millilitres/litres), or count as applicable. Abbreviations must conform to SI conventions.',
    category: 'Packaged Commodities',
    version: '2026.1',
    effectiveDate: '2026-01-01',
    source: 'Legal Metrology (Packaged Commodities) Rules',
    mandatory: true,
  },
  {
    id: 'LM-R003',
    name: 'Maximum Retail Price (MRP)',
    description: 'MRP must be declared as a single all-inclusive price inclusive of all taxes. No additional charges beyond MRP shall be collected.',
    category: 'Packaged Commodities',
    version: '2026.1',
    effectiveDate: '2026-01-01',
    source: 'Legal Metrology (Packaged Commodities) Rules',
    mandatory: true,
  },
  {
    id: 'LM-R004',
    name: 'Country of Origin',
    description: 'Every imported packaged commodity shall declare the country of origin or manufacture on the principal display panel.',
    category: 'Imported Commodities',
    version: '2026.1',
    effectiveDate: '2026-01-01',
    source: 'Legal Metrology (Packaged Commodities) Rules',
    mandatory: true,
  },
  {
    id: 'LM-R005',
    name: 'Consumer Care Details',
    description: 'Each package must provide consumer care information — a telephone number, email address or postal address for consumer grievance redressal.',
    category: 'Packaged Commodities',
    version: '2026.1',
    effectiveDate: '2026-01-01',
    source: 'Legal Metrology (Packaged Commodities) Rules',
    mandatory: true,
  },
  {
    id: 'LM-R006',
    name: 'Date of Manufacture / Packing',
    description: 'Month and year of manufacture or packing shall be declared. For fast-moving commodities, best-before or use-by date is also required.',
    category: 'Packaged Commodities',
    version: '2026.1',
    effectiveDate: '2026-01-01',
    source: 'Legal Metrology (Packaged Commodities) Rules',
    mandatory: true,
  },
  {
    id: 'LM-R007',
    name: 'Font Size Requirements',
    description: 'Declarations shall be made in a font size not less than 1mm height for packages up to 200g/200ml, and proportionally larger for larger packages.',
    category: 'Packaged Commodities',
    version: '2026.1',
    effectiveDate: '2026-01-01',
    source: 'Legal Metrology (Packaged Commodities) Rules',
    mandatory: true,
  },
  {
    id: 'LM-R008',
    name: 'Batch / Lot Number',
    description: 'Batch number, lot number, or code number enabling the source of manufacture to be traced shall appear on each package.',
    category: 'Packaged Commodities',
    version: '2026.1',
    effectiveDate: '2026-01-01',
    source: 'Legal Metrology (Packaged Commodities) Rules',
    mandatory: false,
  },
];

export const DEMO_INSPECTION: Inspection = {
  id: 'INS-2026-00147',
  createdAt: '2026-09-09T10:42:00Z',
  inspectorId: 'LM-OFF-0042',
  inspectorName: 'Rajesh Kumar',
  location: 'Big Bazaar, Sector 18, Noida',
  overallStatus: 'NON_COMPLIANT',
  product: {
    id: 'PROD-001',
    name: 'Premium Face Moisturiser SPF 30',
    brand: 'LuminaCare',
    category: 'Personal Care',
    isImported: true,
    previousInspections: 3,
  },
  images: [
    {
      id: 'IMG-001',
      side: 'FRONT',
      url: '',
      capturedAt: '2026-09-09T10:42:15Z',
      qualityScore: 91,
      qualityChecks: {
        resolution: 'GOOD',
        orientation: 'GOOD',
        packageDetected: true,
        textVisibility: 'GOOD',
        blur: 'LOW',
        lighting: 'GOOD',
      },
    },
    {
      id: 'IMG-002',
      side: 'BACK',
      url: '',
      capturedAt: '2026-09-09T10:42:38Z',
      qualityScore: 84,
      qualityChecks: {
        resolution: 'GOOD',
        orientation: 'GOOD',
        packageDetected: true,
        textVisibility: 'GOOD',
        blur: 'LOW',
        lighting: 'GOOD',
      },
    },
  ],
  evidence: [
    {
      id: 'EV-001',
      type: 'PRODUCT_NAME',
      label: 'Product Name',
      value: 'Premium Face Moisturiser SPF 30',
      confidence: 96,
      imageId: 'IMG-001',
      source: 'OCR+VISION',
      status: 'FOUND',
      rawEvidence: '"Premium Face Moisturiser SPF 30" — front panel, upper third',
    },
    {
      id: 'EV-002',
      type: 'NET_QUANTITY',
      label: 'Net Quantity',
      value: '50 ml',
      confidence: 94,
      imageId: 'IMG-001',
      source: 'OCR',
      status: 'FOUND',
      rawEvidence: '"Net Qty: 50 ml" — front panel, lower section',
    },
    {
      id: 'EV-003',
      type: 'MRP',
      label: 'MRP',
      value: '₹899',
      confidence: 92,
      imageId: 'IMG-001',
      source: 'OCR',
      status: 'FOUND',
      rawEvidence: '"MRP: ₹899 (Incl. of all taxes)" — front panel',
      conflictingValues: [
        { imageId: 'IMG-001', value: '₹899', side: 'FRONT' },
      ],
    },
    {
      id: 'EV-004',
      type: 'MANUFACTURER',
      label: 'Manufacturer / Importer',
      value: 'LuminaCare International Pvt. Ltd., Mumbai — 400 001',
      confidence: 88,
      imageId: 'IMG-002',
      source: 'OCR',
      status: 'FOUND',
      rawEvidence: '"Imported and marketed by LuminaCare International Pvt. Ltd."',
    },
    {
      id: 'EV-005',
      type: 'MFG_DATE',
      label: 'Manufactured On',
      value: 'Jun 2026',
      confidence: 90,
      imageId: 'IMG-002',
      source: 'OCR',
      status: 'FOUND',
      rawEvidence: '"Mfg: Jun 2026"',
    },
    {
      id: 'EV-006',
      type: 'EXPIRY',
      label: 'Best Before',
      value: 'Jun 2028',
      confidence: 91,
      imageId: 'IMG-002',
      source: 'OCR',
      status: 'FOUND',
      rawEvidence: '"Best Before: Jun 2028"',
    },
    {
      id: 'EV-007',
      type: 'CONSUMER_CARE',
      label: 'Consumer Care',
      value: 'Not clearly detected',
      confidence: 38,
      imageId: 'IMG-002',
      source: 'OCR',
      status: 'UNCERTAIN',
      rawEvidence: 'Partial text near bottom of back panel — illegible in current image',
    },
    {
      id: 'EV-008',
      type: 'COUNTRY_OF_ORIGIN',
      label: 'Country of Origin',
      value: 'Not detected',
      confidence: 12,
      imageId: 'IMG-002',
      source: 'OCR+VISION',
      status: 'NOT_FOUND',
      rawEvidence: 'No country-of-origin declaration identified in available images',
    },
    {
      id: 'EV-009',
      type: 'BATCH_NUMBER',
      label: 'Batch / Lot Number',
      value: 'BT2026-0614-A',
      confidence: 85,
      imageId: 'IMG-002',
      source: 'OCR',
      status: 'FOUND',
      rawEvidence: '"Batch: BT2026-0614-A"',
    },
  ],
  applicableRequirements: [
    {
      id: 'REQ-001',
      ruleId: 'LM-R001',
      name: 'Product Name',
      description: 'Common or generic name of the commodity must be clearly declared.',
      applicability: 'All packaged commodities',
    },
    {
      id: 'REQ-002',
      ruleId: 'LM-R002',
      name: 'Net Quantity',
      description: 'Net quantity declared in standard SI units.',
      applicability: 'All packaged commodities',
    },
    {
      id: 'REQ-003',
      ruleId: 'LM-R003',
      name: 'Maximum Retail Price',
      description: 'MRP inclusive of all taxes must be declared.',
      applicability: 'All packaged commodities sold in India',
    },
    {
      id: 'REQ-004',
      ruleId: 'LM-R001',
      name: 'Manufacturer / Importer Details',
      description: 'Name and address of manufacturer, packer, or importer must be declared.',
      applicability: 'All packaged commodities',
    },
    {
      id: 'REQ-005',
      ruleId: 'LM-R006',
      name: 'Date of Manufacture',
      description: 'Month and year of manufacture or packing must be clearly declared.',
      applicability: 'All packaged commodities',
    },
    {
      id: 'REQ-006',
      ruleId: 'LM-R005',
      name: 'Consumer Care Details',
      description: 'Telephone number, email, or postal address for consumer grievance.',
      applicability: 'All packaged commodities',
    },
    {
      id: 'REQ-007',
      ruleId: 'LM-R004',
      name: 'Country of Origin',
      description: 'Country of origin/manufacture must be declared for imported commodities.',
      applicability: 'Imported packaged commodities',
    },
    {
      id: 'REQ-008',
      ruleId: 'LM-R008',
      name: 'Batch / Lot Number',
      description: 'Batch or lot number enabling traceability of manufacture.',
      applicability: 'All packaged commodities',
    },
  ],
  findings: [
    {
      id: 'FND-001',
      requirementId: 'REQ-001',
      status: 'COMPLIANT',
      evidenceIds: ['EV-001'],
      ruleId: 'LM-R001',
      explanation: 'Product name "Premium Face Moisturiser SPF 30" is clearly declared on the front panel with high confidence.',
      recommendation: '',
      confidence: 96,
      reviewRequired: false,
    },
    {
      id: 'FND-002',
      requirementId: 'REQ-002',
      status: 'COMPLIANT',
      evidenceIds: ['EV-002'],
      ruleId: 'LM-R002',
      explanation: 'Net quantity "50 ml" declared in standard SI units on the front panel.',
      recommendation: '',
      confidence: 94,
      reviewRequired: false,
    },
    {
      id: 'FND-003',
      requirementId: 'REQ-003',
      status: 'COMPLIANT',
      evidenceIds: ['EV-003'],
      ruleId: 'LM-R003',
      explanation: 'MRP ₹899 inclusive of all taxes is clearly declared on front panel.',
      recommendation: '',
      confidence: 92,
      reviewRequired: false,
    },
    {
      id: 'FND-004',
      requirementId: 'REQ-004',
      status: 'COMPLIANT',
      evidenceIds: ['EV-004'],
      ruleId: 'LM-R001',
      explanation: 'Importer name and address clearly present on back panel.',
      recommendation: '',
      confidence: 88,
      reviewRequired: false,
    },
    {
      id: 'FND-005',
      requirementId: 'REQ-005',
      status: 'COMPLIANT',
      evidenceIds: ['EV-005'],
      ruleId: 'LM-R006',
      explanation: 'Manufacturing date "Jun 2026" found on back panel.',
      recommendation: '',
      confidence: 90,
      reviewRequired: false,
    },
    {
      id: 'FND-006',
      requirementId: 'REQ-006',
      status: 'VERIFICATION_REQUIRED',
      evidenceIds: ['EV-007'],
      ruleId: 'LM-R005',
      explanation: 'Consumer care details were not clearly identified in available images. Partial text detected near the bottom of the back panel but insufficient for verification.',
      recommendation: 'Capture a close-up of the bottom section of the back panel where consumer care details may be printed.',
      confidence: 38,
      reviewRequired: true,
    },
    {
      id: 'FND-007',
      requirementId: 'REQ-007',
      status: 'NON_COMPLIANT',
      evidenceIds: ['EV-008'],
      ruleId: 'LM-R004',
      explanation: 'No country-of-origin declaration was detected in available front and back panel images. This product is classified as an imported packaged commodity and this declaration is mandatory.',
      recommendation: 'Inspect all panels physically. If country of origin is absent, this constitutes a mandatory declaration violation.',
      confidence: 88,
      reviewRequired: true,
    },
    {
      id: 'FND-008',
      requirementId: 'REQ-008',
      status: 'COMPLIANT',
      evidenceIds: ['EV-009'],
      ruleId: 'LM-R008',
      explanation: 'Batch number BT2026-0614-A found on back panel.',
      recommendation: '',
      confidence: 85,
      reviewRequired: false,
    },
  ],
  inspectorDecisions: [],
  remarks: '',
};

export const RECENT_INSPECTIONS: Array<{
  id: string;
  productName: string;
  category: string;
  date: string;
  status: 'COMPLIANT' | 'NON_COMPLIANT' | 'VERIFICATION_REQUIRED';
}> = [
  {
    id: 'INS-2026-00147',
    productName: 'Premium Face Moisturiser SPF 30',
    category: 'Personal Care',
    date: 'Today, 10:42 AM',
    status: 'NON_COMPLIANT',
  },
  {
    id: 'INS-2026-00146',
    productName: 'Amul Taaza Full Cream Milk',
    category: 'Food & Grocery',
    date: 'Today, 09:15 AM',
    status: 'COMPLIANT',
  },
  {
    id: 'INS-2026-00145',
    productName: 'Surf Excel Matic Liquid',
    category: 'Household',
    date: 'Yesterday',
    status: 'COMPLIANT',
  },
  {
    id: 'INS-2026-00144',
    productName: 'Imported Herbal Tea (Organic)',
    category: 'Food & Grocery',
    date: 'Yesterday',
    status: 'VERIFICATION_REQUIRED',
  },
  {
    id: 'INS-2026-00143',
    productName: 'Nycil Cool Powder',
    category: 'Personal Care',
    date: '07 Sep 2026',
    status: 'COMPLIANT',
  },
];
